### ISSUE TITLE
Git/Github and Agile Training

### ISSUE THREAD

**Issue by fabiolamfleury** [fga-eps-mds/2019.2-TimeBolinho#1]
Introduce concepts about Agile metodologies (Scrum and XP) and Git/Github. Also there will be praticle portion so that theory can be better understood

**When**: 17/08/2019 14:00-18:00

**Comment by MarthaDs** [comment]
Link of repository we'll use today on the workshop: https://github.com/MarthaDs/workshop-scrum-git

**Comment by vitorcx** [comment]
Training done from 14h to 18h on 17/08 at FGA.
Here is the link to the issues refering the "product" developed in the workshop practical activity:
https://github.com/MarthaDs/workshop-scrum-git/issues?q=is%3Aissue+is%3Aclosed
