### ISSUE TITLE
HTML CSS Training

### ISSUE THREAD

**Issue by shayanealcantara** [fga-eps-mds/2019.2-TimeBolinho#10]
### Description:
Training about HTML and CSS

### Acceptance standards:
- Present basic flow to the development team so they can be more familiar about it and propose some practical activity.  
- Training results has to be commited to: https://github.com/MarthaDs/TreinaBolinho

### Tasks:

- [x] Training planning
- [x] To present the planning

**Comment by MarthaDs** [comment]
Training done from 14h to 18h on 24/08 at FGA.
Here is the link to the issues refering the "product" developed in the workshop practical activity:
https://github.com/MarthaDs/TreinaBolinho/tree/treinamento-html-css
![photo_2019-08-26_09-31-43](https://user-images.githubusercontent.com/12221656/63691022-8509e580-c7e4-11e9-8b7b-ab508ead64f9.jpg)
