### ISSUE TITLE
Present project good practices 

### ISSUE THREAD

**Issue by shayanealcantara** [fga-eps-mds/2019.2-TimeBolinho#11]
### Description:
Introduce git flow to the development team so the whole group can work 

### Acceptance standards:
- Good practices and policies to commits, branches and pull requests created in #7 

### Tasks:

- [x] Present the developed documentation created for that purpose

**Comment by fabiolamfleury** [comment]
During our meeting (24th august) repository [policies ](https://fga-eps-mds.github.io/2019.2-TimeBolinho/#/policies) were showed and explained.

All members were present.
