### ISSUE TITLE
Estudo sobre a arquitetura do projeto

### ISSUE THREAD

**Issue by shayanealcantara** [fga-eps-mds/2019.2-TimeBolinho#12]
### Descrição:
Estudo sobre a arquitetura do projeto de acordo com o tema definido.

### Critérios de aceitação:
- Verificar viabilidade

### Tarefas:

- [ ] Monolítico VS Micro serviço
- [ ] Justificar e compartilhar com a equipe

**Comment by MarthaDs** [comment]
Não se aplica mais ao contexto do projeto
