### ISSUE TITLE
Criar documento de visão

### ISSUE THREAD

**Issue by fabiolamfleury** [fga-eps-mds/2019.2-TimeBolinho#15]
depende da issue #4 

### Descrição

Elaborar documento de visão para ter uma melhor visão do produto

### Critérios de aceitação

- [x] Deve estar na língua portuguesa

- [x] Deve ser escrito de forma colaborativa pelos membros de MDS

- [x] Deve ser desenvolvido de acordo com as [políticas de repositório](https://fga-eps-mds.github.io/2019.2-TimeBolinho/#/policies)

### Tarefas

- [x]  Criar a estrutura do documento

- [x] Preencher documento com o conteúdo específico

- [ ] Revisão do documento

**Comment by RenatoBrittoAraujo** [comment]
Pergunta sobre o Saskatoon: Os beneficiários se candidatam a receber doações ou a Les Fruits Défendus recebe as doações e depois decide para quais instituições as doações vão? Como funciona o sistema de beneficiários?

**Comment by LeoSilvaGomes** [comment]
Como o resumo de capacidades é uma parte onde agrega os benefícios para o cliente/usuário e os recursos de suporte (que são referentes aos benefícios), eu devo fazer um para um pseudo cliente, tendo em vista que não temos um?

**Comment by fabiolamfleury** [comment]
> depois decide para quais instituições as doações vão? Como funciona o sistema de beneficiários?

![image](https://user-images.githubusercontent.com/20935369/64203861-c9435880-ce6a-11e9-984a-ec0672864f1e.png)

**Comment by fabiolamfleury** [comment]
> Como o resumo de capacidades é uma parte onde agrega os benefícios para o cliente/usuário e os recursos de suporte (que são referentes aos benefícios), eu devo fazer um para um pseudo cliente, tendo em vista que não temos um?


Os benefícios podem ser mapeados fazendo comparativos em relação a como é feito atualmente (outros produtos, como o saskatoon, ou mesmo pensar no "boca-a-boca")

Criar um cliente não é o ideal, mas sim responder a pergunta: O que a nossa solução propõe de melhor do que já existe no mercado?

**Comment by durvalcarvalho** [comment]
Todos os tópicos destinados ao grupo de MDS foram escritos. Agora é preciso revisar os textos para corrigir eventuais erros.

**Comment by LeoSilvaGomes** [comment]
> > Como o resumo de capacidades é uma parte onde agrega os benefícios para o cliente/usuário e os recursos de suporte (que são referentes aos benefícios), eu devo fazer um para um pseudo cliente, tendo em vista que não temos um?
> 
> Os benefícios podem ser mapeados fazendo comparativos em relação a como é feito atualmente (outros produtos, como o saskatoon, ou mesmo pensar no "boca-a-boca")
> 
> Criar um cliente não é o ideal, mas sim responder a pergunta: O que a nossa solução propõe de melhor do que já existe no mercado?

Imagino que isso tenho sido resolvido, como pode ser visto no documento de visão preenchido. Obrigado.
