### ISSUE TITLE
Docker Training

### ISSUE THREAD

**Issue by fabiolamfleury** [fga-eps-mds/2019.2-TimeBolinho#2]
Introduce concepts about Docker and containers. Also there will be praticle portion so that theory can be better understood

When: 21/08/2019 12:00-13:00

**Comment by MarthaDs** [comment]
Treinamento feito das 12h as 13h em 21/08 na FGA.
Segue o link do slide usado no treinamento:
https://drive.google.com/open?id=10koxLpB2-Ph12c-fy9nmjUYwaxc4kfqHPc5q5AzWTu4
![photo_2019-08-31_15-36-11](https://user-images.githubusercontent.com/12221656/64067859-9a787880-cc05-11e9-8c38-7be423fd144f.jpg)
