### ISSUE TITLE
Definir as Tecnologias da Arquitetura

### ISSUE THREAD

**Issue by MarthaDs** [fga-eps-mds/2019.2-TimeBolinho#20]
### Descrição:

Fazer um estudo das tecnologias e definir quais tecnologias atendem melhor ao escopo do projeto.

### Tasks:

- [x] Verificar a viabilidade de usar as tecnologias escolhidas.
- [x] Documentar no git pages quais são as tecnologias escolhidas

**Comment by shayanealcantara** [comment]
Possibilidades de tecnologias:

1. Back-end: 
- Django

2. Front-end (algumas opções para descutir a princípio):
<img src="https://user-images.githubusercontent.com/33501171/64123436-bf422c80-cd7a-11e9-89df-39efa605b7cb.png" width="200"/>

- Vue
- React

**Comment by shayanealcantara** [comment]
[React vs Vue](https://medium.com/fundbox-engineering/react-vs-vue-vs-angular-163f1ae7be56)

**Comment by shayanealcantara** [comment]
- Tempo
- Escopo grande
- Familiaridade com as tecnologias
- Curva de aprendizado

**Comment by shayanealcantara** [comment]
@MarthaDs Como você acha que fica melhor a estrutura da documentação dessa decisão no github pages?
