### ISSUE TITLE
Definir Indicadores e Métricas

### ISSUE THREAD

**Issue by MarthaDs** [fga-eps-mds/2019.2-TimeBolinho#24]
### Descrição:

Estudar e definir indicadores e metricas de produtividade, gerenciamento de riscos e manutenção.

### Tarefas:

- [x] Estudar Indicadores e Métricas;
- [x] Criar documento no git pages;
- [x] Documentar indicadores e métricas.

#### Critérios de Aceitação:

- [x] Definir Indicadores;
- [x] Definir Métricas;
- [x] Documentar no git pages os indicadores e métricas definidos;
- [ ] Apresentar indicadores e métricas a equipe.

**Comment by shayanealcantara** [comment]
@MarthaDs Como está o andamento desta issue? Quer ajuda se não tiver finalizado ainda?

**Comment by MarthaDs** [comment]
Estou finalizando o documento. Colocando as imagens que faltam

**Comment by MarthaDs** [comment]
Fiz um pull request do documento com a primeira versao finalizada.
