### ISSUE TITLE
Estudo sobre Progressive Web App

### ISSUE THREAD

**Issue by shayanealcantara** [fga-eps-mds/2019.2-TimeBolinho#3]
### Descrição:
Estudo sobre a tecnologia PWA (Progressive Web App) no contexto do projeto para verificar se a equipe poderá usufruir ou não dela..

### Critérios de aceitação:
- Deve ser feito um estudo verificando o contexto do projeto e as regras de negócio.

### Tarefas:

- [ ] Verificar viabilidade
- [ ] Justificar e compartilhar com a equipe

**Comment by MarthaDs** [comment]
Não se aplica mais ao contexto do projeto
