### ISSUE TITLE
Criar Guia de Estilo

### ISSUE THREAD

**Issue by fabiolamfleury** [fga-eps-mds/2019.2-TimeBolinho#35]
### Descrição:
Criar guia de estilo

### Critérios de aceitação:

- Deve ser documentado no github pages
- Deve possuir as principais características de design do produto

### Tarefas:

- [x]  Definir palheta de cores

- [x] Identidade visual

- [x] Nome da aplicação

- [x] Guias de cores, fontes e botões

**Comment by KiSobral** [comment]
Algumas logomarcas já foram pensadas e esboçadas.
![all_logos](https://user-images.githubusercontent.com/43852963/64573733-cf41a980-d342-11e9-8e87-f740e43051c1.jpg)

___
A primeira, pensada dessa forma pra demonstrar a valorização de uma colheita.
![logo_1](https://user-images.githubusercontent.com/43852963/64573861-4d05b500-d343-11e9-852d-6e3f3bdfe5d4.jpg)

___
A segunda tenta transmitir uma sensação de "englobar" com um fruto envolto em uma mão.
![logo_2](https://user-images.githubusercontent.com/43852963/64573963-c0a7c200-d343-11e9-8b52-e326f5a4199f.jpg)

___
A terceira mostra duas mãos que se entrelaçam e possuem caracterísitcas físicas e aspectos de árvores.
![logo_3](https://user-images.githubusercontent.com/43852963/64573966-c69da300-d343-11e9-9fe4-c2eb9a0fc87c.jpg)

___
A quarta possui um visual predominantemente limpo e se inspira em um dos principais elementos do projeto: uma árvore.
![logo_4](https://user-images.githubusercontent.com/43852963/64573969-cb625700-d343-11e9-9f49-fc77c28a73e8.jpg)

**Comment by fabiolamfleury** [comment]
Bom trabalho! Acredito que as marcas conseguiram traduzir o contexto do projeto. Coloco a ressalva dessa última imagem, que usa linhas retas, que embora tem relação com estabilidade, também é uma coisa "mais dura", exata, acredito que imagens com curvas traduzem melhor o senso de comunidade, união.

**Comment by shayanealcantara** [comment]
Link para auxiliar na escolha das cores com o contraste adequado. Pelo que eu lembre o valor de referência adequado é a partir de 4.5 https://contrast-ratio.com/

**Comment by KiSobral** [comment]
Sobre a escolha do nome da aplicação, teve-se a ideia de utilizar **Acacia**, em português **Acácia**

O nome foi escolhido por conta da história por trás da planta acácia: A acácia é uma árvore que participa de uma relação **_interespecífica, harmônica e facultativa_**, com formigas, chamada de **_Protocooperação_**. Isto é, nem a árvore e nem as formigas, _espécies diferentes_, tem a necessidade de participar deste processo, mas ambas se beneficiam caso optem por cooperar.

Tal conceito se relaciona com o propósito do nosso projeto de colaboração voluntária e estimulação do senso de comunidade.

**Comment by LeoSilvaGomes** [comment]
> Testes de componentes. @LeoSilvaGomes @KiSobral sugestões?
> 
> ![image](https://user-images.githubusercontent.com/20935369/64827053-43758a80-d599-11e9-870c-10f4e6e507fd.png)

Gostei muito da segunda composição de botões, entretanto o checkbox em circulo fica melhor.
Sinto que deveríamos testar acácia sem a logo principal no header para ver como fica.

**Comment by LeoSilvaGomes** [comment]
![esboço_logofruta](https://user-images.githubusercontent.com/38738836/64890608-7164d880-d646-11e9-9ed2-959d0e82f877.jpg)

Após alguns desenhos, foi feito o esboço dessa logo, que é composta de uma folha, uma semente e uma fruta, no qual a mesma tem um formato arredondado, pensando no imagem do aplicativo.

**Comment by LeoSilvaGomes** [comment]
Foi decidido passar o desenho para os programas de edição de imagem, no qual vetorizamos a logo.
Podemos perceber que foi feito dois modelos, uma fruta sendo uma maçã e a outra uma laranja. Além disso também há modelos divergentes dos que foram feitos no papel, onde a fruta aparece cortada.

![Ativo 3@4x-100](https://user-images.githubusercontent.com/38738836/64891569-a7a35780-d648-11e9-83b2-c3954f7db7bd.jpg)

**Comment by LeoSilvaGomes** [comment]
Após a decisão do nome, houve uma discussão para a simbologia da logo no projeto, mediante isto, foi decidido fazer uma logo que acarretasse o significado do nome ou abrangesse o projeto. Por isso, foi feito uma logo diretamente no programa de edição de imagem, que se assemelha a um ramo da árvore Acácia,  o mesmo é composto pelas cores amarelas, que sofreu algumas alterações em seu tom depois da decisão das cores.

Após alguns estudos, foi feito a logo monocromática. Baseada na logo principal, a logo monocromática é constituída do contorno dos círculos que compõe a logo principal.

Feito em:   11/09/2019

![Ativo 4@4x-100](https://user-images.githubusercontent.com/38738836/64892082-df5ecf00-d649-11e9-9175-014de11a2785.jpg)

**Comment by LeoSilvaGomes** [comment]
Entre as pessoas da issue, foi decidido que iriamos dar continuidade a logo mais recente, assim foi feita uma wordmark, ou seja, uma logo que agregasse o nome do projeto e sua logo. Foi decidido fazer isso pela grande chance de utilização da logo na página, onde há no momento, uma variedade considerável de logo para compor a plataforma. A mesma deva se utilizada em grandes divulgações ou apresentações do projeto.

Feito: 11/09/2019

![Ativo 5@4x-100](https://user-images.githubusercontent.com/38738836/64892393-aecb6500-d64a-11e9-88e0-8dcbb8df2a61.jpg)
