### ISSUE TITLE
Criar o Termo de Abertura do Projeto (TAP)

### ISSUE THREAD

**Issue by shayanealcantara** [fga-eps-mds/2019.2-TimeBolinho#4]
### Description:

Desenvolver o TAP de acordo com o projeto de Sistema de Colheita Colaborativa.

Alguns exemplos podem ser encontrados [aqui](https://github.com/fga-eps-mds/A-Disciplina/blob/master/GPP_Material/04%20-%20inicializacao/Project-Charter.doc) e [aqui](https://github.com/fga-eps-mds/2018.2-Integra-Vendas/blob/master/docs/docs/tap.md)

###  Critérios de aceitação

- Texto deve estar nas github pages, em português

### Tarefas:

- [x] Adicionar partes interessadas;
- [x] Descrever escopo e problema;
- [x] Adicionar os papéis da equipe;
- [x] ...

**Comment by fabiolamfleury** [comment]
Falta atualizar os custos para acrescentar o membro que entrou depois no time e também o delta risco e o delta lucro
